name: DEB builder git

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  Linux-deb:
    runs-on: ubuntu-latest
    
    steps:
    - name: setup makedeb
      run: |
        wget -qO - 'https://proget.hunterwittenborn.com/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg &> /dev/null
        echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.hunterwittenborn.com/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
        sudo apt-get update
        sudo apt-get install -y makedeb
        
    - name: clone repo
      uses: actions/checkout@v1
      with:
        submodules: 'true'    
        
    - name: makedeb bug workaround # https://github.com/makedeb/makedeb/issues/30
      run: |
        sudo apt-get install -y python3 python3-pip python3-pyqt5 python3-uinput python3-ruamel.yaml python3-usb libnotify-bin
        mv ./linux_packaging/DEBBUILD-git ./linux_packaging/PKGBUILD        
        
    - name: build deb package (git)
      run: cd ./linux_packaging && makedeb

    - name: save deb file
      uses: actions/upload-artifact@master
      with:
        name: G910-gui-git
        path: ./linux_packaging/*.deb
