name: DEB builder

on:
  push:
    tags:
    - '*'

jobs:
  Linux-deb:
    runs-on: ubuntu-latest
    
    steps:
    - name: setup makedeb
      run: |
        wget -qO - 'https://proget.hunterwittenborn.com/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg &> /dev/null
        echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.hunterwittenborn.com/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
        sudo apt-get update
        sudo apt-get install -y makedeb
        
    - name: clone MPR-git repo
      run: git clone https://mpr.hunterwittenborn.com/keyboard-center.git

    - name: build deb package
      run: cd ./keyboard-center && makedeb -s

    - name: save deb file
      uses: actions/upload-artifact@master
      with:
        name: keyboard-center
        path: ./keyboard-center/*.deb
